# Default options for running qiime2 with slurm
rerun-incomplete: True
rerun-triggers: "mtime"
latency-wait: 90
jobs: 100
keep-going: True
notemp: True
printshellcmds: True
nolock: True
verbose: True
cores: 24 # 'all' uses all available cores, you can also specify a number
cluster: "sbatch \
          --account={resources.account} \
          --partition={resources.partition} \
          --mem={resources.mem_mb} \
          --cpus-per-task={threads} \
          --time={resources.runtime} \
          --job-name={rule} \
          --output=slurm_%x_%j.out"

# Default resource configuration
default-resources:
  - account="hpcusers"
  - partition="defq"
  - runtime=120
  - mem_mb=4000
  - disk_mb=1000
# set-threads: map rule names to threads
set-threads:
  - run_vsearch=4
  - run_dada2=8
  - picrust2=8
# set-resources: map rule names to resources in general
set-resources:
  - run_dada2:mem_mb=16000
  - run_dada2:runtime=2880
  - dada2_assignSpecies:mem_mb=32000
  - dada2_assignSpecies:runtime=1440
  - get_taxonomy:mem_mb=32000
  - get_taxonomy:runtime=1440
  - picrust2:mem_mb=32000
  - picrust2:runtime=4320

configfile: "/mnt/isilon/microbiome/analysis/userid/16S_QIIME2/qiime2_config.yml"
