all:
    project_dir: "/scr1/users/danielsg/dana_graves_run_1/Data"
    mux_dir: "multiplexed_fastq"
    mapping: "Graves_Dana_Run_1_mapping_file.tsv"
    admin_email: "danielsg@chop.edu"

#try revcomp if you are getting 0 reads when demultiplexing
demux:
    mismatch: 0
    revcomp: true

#~240 for V1V2, ~280 for V3V4
denoise:
    trim_left_f: 0
    trunc_len_f: 240
    trim_left_r: 0
    trunc_len_r: 240
    n_threads: 8

taxonomy:
    classifier_fp: "/mnt/isilon/microbiome/analysis/biodata/silva/silva_132/silva-132-99-nb-classifier.qza"

diversity:
    sampling_depth: 1000

unassign:
    unassigner_species_fp: "/mnt/isilon/microbiome/analysis/biodata/unassigner/unassigner_species.fasta"

dada2:
    rscript: "/mnt/isilon/microbiome/analysis/biodata/dada2/dada2.R"
    species_training_set: "/mnt/isilon/microbiome/analysis/biodata/dada2/rdp_species_assignment_18.fa.gz"
    #if you want to use SILVA:
    #species_training_set: "/mnt/isilon/microbiome/analysis/biodata/dada2/silva_species_assignment_v138.1.fa.gz"

vsearch:
    db: "/mnt/isilon/microbiome/analysis/biodata/green_genes/current_gg16S.fasta"
    threads: 4
    min_id: 0.97 #minimum identity for query-target match
    weak_id: 0.97 #set lower than min-id and you will get some weaker matches too
    userfields: "query+target+id2+alnlen+mism+gaps+qilo+qihi+tilo+tihi+qs+ts+qrow+trow" #fields for results file, see vsearch documentation for details
    iddef: 2 #the way "identity" is calculated, see vsearch docs for details (it's equal to (matching columns) / (alignment length) excluding terminal gaps)
    fasta_width: 0 #Width of alignment lines in fasta output, set to 0 to eliminate wrapping
    maxaccepts: 1 #Maximum number of hits to accept before stopping the search Default is 1

picrust:
    threads: 8

# Default options for running qiime2 with slurm
rerun-incomplete: True
rerun-triggers: "mtime"
latency-wait: 90
jobs: 100
keep-going: True
notemp: True
printshellcmds: True
nolock: True
verbose: True
cores: 24 # 'all' uses all available cores, you can also specify a number
cluster: "sbatch \
          --account={resources.account} \
          --partition={resources.partition} \
          --mem={resources.mem_mb} \
          --cpus-per-task={threads} \
          --time={resources.runtime} \
          --job-name={rule} \
          --output=slurm_%x_%j.out"

# Default resource configuration
default-resources:
  - account="hpcusers"
  - partition="defq"
  - runtime="2:0:0"
  - mem_mb=4000
  - disk_mb=1000
# set-threads: map rule names to threads
set-threads:
  - run_vsearch=4
  - run_dada2=8
  - picrust2=8
# set-resources: map rule names to resources in general
set-resources:
  - run_dada2:mem_mb=16000
  - run_dada2:runtime="48:0:0"
  - dada2_assignSpecies:mem_mb=32000
  - dada2_assignSpecies:runtime="24:0:0"
  - get_taxonomy:mem_mb=32000
  - get_taxonomy:runtime="24:0:0"
  - picrust2:mem_mb=32000
  - picrust2:runtime="72:0:0"

#this might be necessary to split off the project specific config
#rather than mashing together with the platform specific config
#configfile: "/mnt/isilon/microbiome/analysis/danielsg/16S_QIIME2/qiime2_config.yml"
