all:
    project_dir: "/scr1/users/danielsg/davis_run_3_16s/Data"
    mux_dir: "multiplexed_fastq"
    mapping: "Davis_run_3_mapping_file.tsv"
    admin_email: ""

#try revcomp if you are getting 0 reads when demultiplexing
demux:
    mismatch: 0
    revcomp: true

denoise:
    trim_left_f: 0
    trunc_len_f: 230
    trim_left_r: 0
    trunc_len_r: 230
    n_threads: 8

taxonomy:
    classifier_fp: "/mnt/isilon/microbiome/analysis/danielsg/16S_QIIME2/QIIME2_data/gg-13-8-99-nb-classifier.qza"

diversity:
    sampling_depth: 30

unassign:
    unassigner_species_fp: "/mnt/isilon/microbiome/analysis/danielsg/16S_QIIME2/unassign_data/unassigner_species.fasta"

report:
    study_group_var: "comparison"
    min_reads: 5
    richness_subsample_size: 20
    rmd: "/mnt/isilon/microbiome/analysis/danielsg/16S_QIIME2/scripts/Basic_Bioinformatics_Report.Rmd"
    R_helper: "/mnt/isilon/microbiome/analysis/danielsg/16S_QIIME2/scripts/helper_functions.R"
    report_rdata: "/scr1/users/danielsg/davis_run_3_16s/Data/report.RData" # rmd can only have one output so have to put this here

dada2:
    rscript: "/mnt/isilon/microbiome/analysis/danielsg/16S_QIIME2/scripts/dada2.R"
    species_training_set: "/mnt/isilon/microbiome/analysis/danielsg/16S_QIIME2/dada2_data/rdp_species_assignment_16.fa.gz"

vsearch:
    db: "/mnt/isilon/microbiome/analysis/biodata/green_genes/current_gg16S.fasta"
    threads: 4
    min_id: 0.97 #minimum identity for query-target match
    weak_id: 0.97 #set lower than min-id and you will get some weaker matches too
    userfields: "query+target+id2+alnlen+mism+gaps+qilo+qihi+tilo+tihi+qs+ts+qrow+trow" #fields for results file, see vsearch documentation for details
    iddef: 2 #the way "identity" is calculated, see vsearch docs for details (it's equal to (matching columns) / (alignment length) excluding terminal gaps)
    fasta_width: 0 #Width of alignment lines in fasta output, set to 0 to eliminate wrapping
    maxaccepts: 1 #Maximum number of hits to accept before stopping the search Default is 1

picrust:
    threads: 8
