all:
    project_dir: "/mnt/isilon/microbiome/analysis/danielsg/16S_QIIME2/test"
    mux_dir: "multiplexed_fastq"
    mapping: "test_mapping_file.tsv"
    admin_email: "danielsg@chop.edu"

#try revcomp if you are getting 0 reads when demultiplexing
demux:
    mismatch: 0
    revcomp: true

#~240 for V1V2, ~280 for V3V4
denoise:
    trim_left_f: 0
    trunc_len_f: 240
    trim_left_r: 0
    trunc_len_r: 240
    n_threads: 8

taxonomy:
    classifier_fp: "/mnt/isilon/microbiome/analysis/biodata/silva/silva_132/silva-132-99-nb-classifier.qza"

diversity:
    sampling_depth: 1000

unassign:
    unassigner_species_fp: "/mnt/isilon/microbiome/analysis/biodata/unassigner/unassigner_species.fasta"

dada2:
    rscript: "/mnt/isilon/microbiome/analysis/biodata/dada2/dada2.R"
    species_training_set: "/mnt/isilon/microbiome/analysis/biodata/dada2/rdp_species_assignment_18.fa.gz"
    #if you want to use SILVA:
    #species_training_set: "/mnt/isilon/microbiome/analysis/biodata/dada2/silva_species_assignment_v138.1.fa.gz"

vsearch:
    db: "/mnt/isilon/microbiome/analysis/biodata/green_genes/current_gg16S.fasta"
    threads: 4
    min_id: 0.97 #minimum identity for query-target match
    weak_id: 0.97 #set lower than min-id and you will get some weaker matches too
    userfields: "query+target+id2+alnlen+mism+gaps+qilo+qihi+tilo+tihi+qs+ts+qrow+trow" #fields for results file, see vsearch documentation for details
    iddef: 2 #the way "identity" is calculated, see vsearch docs for details (it's equal to (matching columns) / (alignment length) excluding terminal gaps)
    fasta_width: 0 #Width of alignment lines in fasta output, set to 0 to eliminate wrapping
    maxaccepts: 1 #Maximum number of hits to accept before stopping the search Default is 1

picrust:
    threads: 8
